<?php

namespace ContainerAxbUaxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RyOtL_UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RyOtL.U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RyOtL.U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'amountRepository' => ['privates', 'App\\Repository\\AmountRepository', 'getAmountRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'amountRepository' => 'App\\Repository\\AmountRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
