<?php

namespace ContainerWmQqSIk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Lt63Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Lt6_3_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Lt6_3_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\indexController::home' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\indexController::insert' => ['privates', '.service_locator.VgZAvnB', 'get_ServiceLocator_VgZAvnBService', true],
            'App\\Controller\\indexController::insert2' => ['privates', '.service_locator.RyOtL.U', 'get_ServiceLocator_RyOtL_UService', true],
            'App\\Controller\\indexController::menu' => ['privates', '.service_locator.URIEtQd', 'get_ServiceLocator_URIEtQdService', true],
            'App\\Controller\\indexController::menuAll' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\indexController:home' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\indexController:insert' => ['privates', '.service_locator.VgZAvnB', 'get_ServiceLocator_VgZAvnBService', true],
            'App\\Controller\\indexController:insert2' => ['privates', '.service_locator.RyOtL.U', 'get_ServiceLocator_RyOtL_UService', true],
            'App\\Controller\\indexController:menu' => ['privates', '.service_locator.URIEtQd', 'get_ServiceLocator_URIEtQdService', true],
            'App\\Controller\\indexController:menuAll' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\indexController::home' => '?',
            'App\\Controller\\indexController::insert' => '?',
            'App\\Controller\\indexController::insert2' => '?',
            'App\\Controller\\indexController::menu' => '?',
            'App\\Controller\\indexController::menuAll' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\indexController:home' => '?',
            'App\\Controller\\indexController:insert' => '?',
            'App\\Controller\\indexController:insert2' => '?',
            'App\\Controller\\indexController:menu' => '?',
            'App\\Controller\\indexController:menuAll' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
