<?php

namespace ContainerNaFexah;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Ks9pPBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Ks9pPB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Ks9pPB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'amountRepository' => ['privates', 'App\\Repository\\AmountRepository', 'getAmountRepositoryService', true],
            'orderId' => ['privates', '.errored..service_locator.8Ks9pPB.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.8Ks9pPB": it references class "App\\Entity\\Order" but no such service exists.'],
            'product' => ['privates', '.errored..service_locator.8Ks9pPB.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.8Ks9pPB": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'amountRepository' => 'App\\Repository\\AmountRepository',
            'orderId' => 'App\\Entity\\Order',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
