<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9lRMhCl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9lRMhCl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9lRMhCl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9lRMhCl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9lRMhCl\App_KernelDevDebugContainer([
    'container.build_hash' => '9lRMhCl',
    'container.build_id' => '938d8744',
    'container.build_time' => 1677007503,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9lRMhCl');
