<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8OA3VTa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8OA3VTa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8OA3VTa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8OA3VTa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8OA3VTa\App_KernelDevDebugContainer([
    'container.build_hash' => '8OA3VTa',
    'container.build_id' => '3c14e1c6',
    'container.build_time' => 1678880748,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8OA3VTa');
