<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKsEi1a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKsEi1a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKsEi1a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKsEi1a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKsEi1a\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKsEi1a',
    'container.build_id' => '339ff1e7',
    'container.build_time' => 1676652007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKsEi1a');
